algoritmo "ATIVIDADE 20"
// Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou ÍMPAR

var

numero: inteiro

inicio

escreval ("DIGITE O VALOR QUE DESEJA VERIFICAR: ")
leia (numero)
escreval ("AGUARDE ENQUANTO VERIFICAMOS! ")
escreval ("O NUMERO DIGITADO FOI: ", numero)

          se(numero %2=0) entao
              escreval("O NUMERO DIGITADO É PAR")
          senao
              escreval (" O NUMERO DIGITADO É IMPAR")
          fimse
          
fimalgoritmo
