algoritmo "ATIVIDADE07"
// Crie um algoritmo que leia um número real
// mostre na tela o seu dobro e a sua terça parte
var
   numero, dobro, terca: real
inicio

      escreva("DIGITE UM NUMERO: ")
      leia(numero)

      dobro <- numero*numero
      terca <- numero/3
      
      escreval(" O dobro de ", numero, " é: ", dobro)
      escreval(" E sua terça parte é: " , terca)
      

fimalgoritmo
